"""testing some new changes

Revision ID: decd4bbb7fe1
Revises: d96da3b190b0
Create Date: 2024-12-15 01:47:55.443734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'decd4bbb7fe1'
down_revision: Union[str, None] = 'd96da3b190b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('col1', sa.Integer(), nullable=True))
    op.add_column('votes', sa.Column('col2', sa.Integer(), nullable=True))
    op.add_column('votes', sa.Column('col3', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_votes_col1'), 'votes', ['col1'], unique=False)
    op.create_index(op.f('ix_votes_col2'), 'votes', ['col2'], unique=False)
    op.create_index(op.f('ix_votes_col3'), 'votes', ['col3'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_col3'), table_name='votes')
    op.drop_index(op.f('ix_votes_col2'), table_name='votes')
    op.drop_index(op.f('ix_votes_col1'), table_name='votes')
    op.drop_column('votes', 'col3')
    op.drop_column('votes', 'col2')
    op.drop_column('votes', 'col1')
    # ### end Alembic commands ###
